version: '3'
services:
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - type: volume
        source: mongo-volume-data
        target: /data/db
    networks:
      - network

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080' # Interfaz web
      - '1025:1025' # Puerto SMTP
    networks:
      - network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - '3001:3001'
    networks:
      - network

  loki:
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    networks:
      - network
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

networks:
  network:
    driver: bridge

volumes:
  mongo-volume-data:
  cache:
    driver: local
  node_modules:
    driver: local
